name: apifile
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  apifile:
    runs-on: ubuntu-latest
    name: build
      
    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install redoc-cli
        run: npm install -g redoc-cli

      - name: Generate API documentation
        run: redoc-cli bundle springdoc-openapi-spring-boot-2-webmvc/src/main/resources/petstore.yml -o openapi.json

      - name: ls
        run : |
          ls

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: 'openapi.json'

      - name: ls
        run : |
          ls
